#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
dry="0"

while [[ $# > 0 ]]; do
  if [[ "$1" == "--dry" ]]; then
    dry="1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute: $@"
  if [[ $dry == "1" ]]; then
    return
  fi

  "$@"
}

log "--------- dev-env (Symlinking) ---------"

cd "$script_dir"

link_dir() {
  pushd "$1" > /dev/null || return
  to="$2"
  mkdir -p "$to"
  dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
  for dir in $dirs; do
    dir_name=$(basename "$dir")
    target_abs="$(realpath "$dir")"
    execute rm -rf "$to/$dir_name"
    execute ln -sfn "$target_abs" "$to/$dir_name"
  done
  popd > /dev/null || return
}

link_file() {
  from="$(realpath "$1")"
  to="$2"
  name=$(basename "$from")
  mkdir -p "$to"
  execute rm -rf "$to/$name"
  execute ln -sfn "$from" "$to/$name"
}

# Symlink main user configs
link_dir .config "$HOME/.config"
link_dir .local "$HOME/.local"
link_file .ready-tmux "$HOME"

# Symlink Pi agent config (.config/pi/agent -> $HOME/.pi/agent)
mkdir -p "$HOME/.pi"
link_file .config/pi/agent "$HOME/.pi"

# Specific config (hypr for omarchy's hyprland config)
# link_dir .config_specific "$HOME/.config"
#
# Specific config (hypr & ghostty for HyDE)
# link_dir .config_HyDE "$HOME/.config"
