#!/usr/bin/env bash

echo "===== Build Neovim ====="
git clone -b v0.11.1 https://github.com/neovim/neovim.git $HOME/personal/neovim
sudo apt install cmake gettext lua5.1 liblua5.1-0-dev

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

echo "===== Install LazyVim ====="
# required
mv ~/.config/nvim ~/.config/nvim{,.bak}

# optional but recommended
mv ~/.local/share/nvim{,.bak}
mv ~/.local/state/nvim{,.bak}
mv ~/.cache/nvim{,.bak}

rm -rf
git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git

echo "===== OPEN nvim, wait for installation to complete then run dev-env script to copy my config ====="
