#!/usr/bin/env bash

git clone -b v0.10.2 https://github.com/neovim/neovim.git $HOME/personal/neovim
sudo apt install cmake gettext lua5.1 liblua5.1-0-dev

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

# required
mv ~/.config/nvim{,.bak}

# optional but recommended
mv ~/.local/share/nvim{,.bak}
mv ~/.local/state/nvim{,.bak}
mv ~/.cache/nvim{,.bak}

git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git
