#!/usr/bin/env bash

echo "=== Install Tmux ==="
sudo pacman -S tmux

echo "=== Install Tmux Plugin Manager ==="
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

echo "=== copy config with dev-env script and then <prefiz>+I ==="
